export const USERS = [
  { id: 1, name: 'Alice Johnson', avatar: 'AJ', role: 'Frontend Dev' },
  { id: 2, name: 'Bob Smith', avatar: 'BS', role: 'Backend Dev' },
  { id: 3, name: 'Carol White', avatar: 'CW', role: 'Designer' },
  { id: 4, name: 'David Lee', avatar: 'DL', role: 'DevOps' },
  { id: 5, name: 'Eva Martinez', avatar: 'EM', role: 'QA Engineer' },
];

export const PROJECTS = [
  {
    id: 1,
    name: 'E-Commerce Platform',
    description: 'Build a full-featured online store with cart, checkout, and payment integration.',
    taskCount: 24,
    completedTasks: 18,
    status: 'Active',
    createdAt: '2024-01-10',
    color: '#6366f1',
  },
  {
    id: 2,
    name: 'Mobile Banking App',
    description: 'Develop a secure mobile banking application with real-time transaction tracking.',
    taskCount: 32,
    completedTasks: 32,
    status: 'Completed',
    createdAt: '2024-01-05',
    color: '#10b981',
  },
  {
    id: 3,
    name: 'Analytics Dashboard',
    description: 'Create an interactive data visualization platform for business intelligence.',
    taskCount: 16,
    completedTasks: 7,
    status: 'Active',
    createdAt: '2024-02-01',
    color: '#f59e0b',
  },
  {
    id: 4,
    name: 'API Gateway Service',
    description: 'Design and implement a scalable API gateway with rate limiting and auth.',
    taskCount: 20,
    completedTasks: 20,
    status: 'Completed',
    createdAt: '2023-12-15',
    color: '#3b82f6',
  },
  {
    id: 5,
    name: 'Customer Portal',
    description: 'Build a self-service customer portal for support tickets and account management.',
    taskCount: 14,
    completedTasks: 4,
    status: 'Active',
    createdAt: '2024-02-20',
    color: '#ef4444',
  },
  {
    id: 6,
    name: 'DevOps Pipeline',
    description: 'Automate CI/CD pipelines for seamless deployment across environments.',
    taskCount: 10,
    completedTasks: 6,
    status: 'Active',
    createdAt: '2024-03-01',
    color: '#8b5cf6',
  },
];

export const INITIAL_TASKS = [
  {
    id: 1,
    title: 'Design system components',
    status: 'Completed',
    assignedTo: 1,
    projectId: 1,
    dueDate: '2024-02-15',
    priority: 'High',
  },
  {
    id: 2,
    title: 'Implement authentication flow',
    status: 'Pending',
    assignedTo: 2,
    projectId: 1,
    dueDate: '2024-03-01',
    priority: 'High',
  },
  {
    id: 3,
    title: 'Set up database schema',
    status: 'Completed',
    assignedTo: 2,
    projectId: 2,
    dueDate: '2024-01-20',
    priority: 'Medium',
  },
  {
    id: 4,
    title: 'Create wireframes for mobile',
    status: 'Pending',
    assignedTo: 3,
    projectId: 2,
    dueDate: '2024-03-10',
    priority: 'Low',
  },
  {
    id: 5,
    title: 'Write API documentation',
    status: 'Pending',
    assignedTo: 4,
    projectId: 4,
    dueDate: '2024-03-05',
    priority: 'Medium',
  },
  {
    id: 6,
    title: 'Performance optimization',
    status: 'Completed',
    assignedTo: 1,
    projectId: 3,
    dueDate: '2024-02-28',
    priority: 'High',
  },
  {
    id: 7,
    title: 'Unit test coverage',
    status: 'Pending',
    assignedTo: 5,
    projectId: 1,
    dueDate: '2024-03-15',
    priority: 'Medium',
  },
  {
    id: 8,
    title: 'Deploy to staging environment',
    status: 'Completed',
    assignedTo: 4,
    projectId: 4,
    dueDate: '2024-02-10',
    priority: 'High',
  },
  {
    id: 9,
    title: 'User acceptance testing',
    status: 'Pending',
    assignedTo: 5,
    projectId: 5,
    dueDate: '2024-03-20',
    priority: 'High',
  },
  {
    id: 10,
    title: 'Security audit and fixes',
    status: 'Pending',
    assignedTo: 2,
    projectId: 2,
    dueDate: '2024-03-25',
    priority: 'High',
  },
  {
    id: 11,
    title: 'Integrate payment gateway',
    status: 'Completed',
    assignedTo: 1,
    projectId: 1,
    dueDate: '2024-02-20',
    priority: 'High',
  },
  {
    id: 12,
    title: 'Configure monitoring alerts',
    status: 'Pending',
    assignedTo: 4,
    projectId: 6,
    dueDate: '2024-03-30',
    priority: 'Medium',
  },
];
